### ISSUE TITLE
Query string params break SSR

### ISSUE THREAD

**Issue by ManuelDeLeon** [antoninadert/proto-starter#1]
Repro: clone repo -> npm i -> meteor

If you go to `http://localhost:3000/` everything is fine.
If you go to `http://localhost:3000/?` the 404 flashes for a sec and you get a console error:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <label class="label" 
 (server) <h1 data-reactroot=""
``` 

This is most likely a problem with the way routes are defined. It's not a VM issue since it happens with a plain React component.

**Comment by antoninadert** [comment]
Indeed if I disable javascript, there is no error and the 404 page is rendered (server-side)
If I enable javascript, there is this warning and the homepage is displayed instead.

It looks like a discrepancy on the way to handle '*' route on the server vs. the client.

I wonder if this has to do with the different package used. You can see that I use universal-router/legacy on server side, and universal-router on client side

**Comment by antoninadert** [comment]
I investigated a little and this seems to have something to do in the difference the URL is identified in the location object from the history package (client side) vs. with the sink object's path (server side)
thatSink.request.url.path (server) ==> Returns '/?'
location.path (client) ==> returns '/'

**Comment by antoninadert** [comment]
Definitely a discrepancy between server-render and history's package way of identifying URLs
for history, when you type '/?' in the URL, it means you have location.path of '/' and location.search of '' (empty)
While on server it means you have location.path of '/?' and no query

**Comment by antoninadert** [comment]
Hi Manuel, 

I merged a new PR for this. Can you tell me if this now behaves like you expect? I used  thatSink.request.url.pathname  instead of thatSink.request.url.path because url.path would expose the query parameters as well, unlike history package which only has a pathname.

Please close if you're happy

**Comment by ManuelDeLeon** [comment]
That works. Thx
